## Difference between Lists And Numpy Arrays

### 1. <u>Type Consistency</u>:
#### Lists in Python can store elements of different data types. For example, you can have a list containing integers, strings, and floats all mixed together.
#### Example: my_list = [1, 'a', 3.14]
#### NumPy arrays are homogeneous, meaning all elements in a NumPy array must be of the same data type.
#### Example: my_array = np.array([1, 2, 3]) (all elements are integers)

### 2. <u>Mathematical Operations</u>:
#### Lists do not support element-wise mathematical operations directly. To perform operations on a list, you typically need to use loops or list comprehensions.
#### Example: Adding two lists would concatenate them, not perform element-wise addition.
#### NumPy arrays support element-wise operations directly. You can add, subtract, multiply, and perform other operations on entire arrays with simple syntax.
#### Example: array1 + array2 performs element-wise addition.

### 3. <u>Multi-dimensional Arrays</u>:
#### While you can create nested lists to simulate multi-dimensional arrays, the operations on such structures are less straightforward and efficient.
#### Example: matrix = [[1, 2], [3, 4]] represents a 2x2 matrix.
#### NumPy provides built-in support for multi-dimensional arrays and operations on them. This includes slicing, reshaping, and more advanced operations.
#### Example: matrix = np.array([[1, 2], [3, 4]])

### 4. <u>Broadcasting</u>:
#### Broadcasting is not supported in standard Python lists. Operations on lists are typically element-wise but not automatically extended across dimensions.
#### NumPy supports broadcasting, which allows for operations between arrays of different shapes in a way that automatically handles dimension mismatch.

## The <u>np.array()</u>

#### Purpose: To create a new NumPy array from any object exposing the array interface (e.g., lists, tuples, other sequences).
#### Always creates a new array, copying the data from the input object.

### Parameters:
#### object: The input data, which can be a list, tuple, or any object that can be converted to an array.
#### dtype: Data type of the resulting array. If not specified, it is inferred from the input data.
#### copy: A boolean indicating whether to create a copy of the data. If True, a new array is always created, even if the input is already an array. If False, a new array is created only if the input is not already an array.

In [1]:
import numpy as np

l = [1, 2, 3, 4]
arr = np.array(l)

print("The array is", arr)
print(type(arr))

The array is [1 2 3 4]
<class 'numpy.ndarray'>


In [20]:
arr1 = np.array([[1, 2], [3, 5]])

print("The 2D array is")
print('\n',arr1,'\n')
print(type(arr1))

# Here arr1 is a 2D array

The 2D array is

 [[1 2]
 [3 5]] 

<class 'numpy.ndarray'>


## The <u>np.asarray()</u>

#### Purpose: Converts the input to an array, but does not create a copy if the input is already an array.

### Parameters:
#### a: The input data, which can be a list, tuple, or any object that can be converted to an array.
#### dtype: Data type of the resulting array. If not specified, it is inferred from the input data.
#### copy: A boolean indicating whether to make a copy of the data. If False, no copy is made if the input is already an array. If True, a new array is created even if the input is already an array.

In [22]:
# Method 2 to convert lists to arrays

arr2 = np.asarray(l)

print("The array is", arr2)
print(type(arr2))

The array is [1 2 3 4]
<class 'numpy.ndarray'>


## The <u>np.asanyarray()</u>

#### Converts the input to an array but preserves subclasses of np.ndarray (such as np.matrix or custom subclasses). It is particularly useful when you want to ensure that the input is treated as an array but retain any special behavior or methods provided by subclasses.

### Parameters:

#### a: The input data, which can be a list, tuple, or any object that can be converted to an array.
#### dtype: Data type of the resulting array. If not specified, it is inferred from the input data.
#### copy: A boolean indicating whether to make a copy of the data. If False, no copy is made if the input is already an array. If True, a new array is created even if the input is already an array.

In [27]:
a = np.asanyarray([1, 2, 3])

print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [29]:
b = np.matrix([1, 2, 3, 4])

print(b)
print(type(b))

[[1 2 3 4]]
<class 'numpy.matrix'>


In [35]:
b_ = np.asanyarray(b)

print(b_)
print(type(b_)) 

# asanyarray() preserves the subclasses

[[1 2 3 4]]
<class 'numpy.matrix'>


In [37]:
b__ = np.asarray(b)

print(b__)
print(type(b__)) 

# asarray() DOES NOT preserve the subclasses

[[1 2 3 4]]
<class 'numpy.ndarray'>


In [45]:
c = np.array([1, 2, 3, 4])

print('The array c is', c)
print(type(c))

d = c # shallow copy

print('\nd represents a shallow copy of c', d)
print(type(d))

The array c is [1 2 3 4]
<class 'numpy.ndarray'>

d represents a shallow copy of c [1 2 3 4]
<class 'numpy.ndarray'>


### A shallow copy is a type of copy where the new object is created, but it only copies references to the objects contained in the original object, rather than copying the actual objects themselves. This means that while the top-level structure is duplicated, the nested objects or elements remain shared between the original and the copied object.

In [48]:
d[0] = 100

print('d is now ', d)
print('Changes made to d reflects for c too', c)

d is now  [100   2   3   4]
Changes made to d reflects for c too [100   2   3   4]


In [52]:
e = np.copy(c) # allows deep copy

print('e a duplicate copy of c', e)

# modifying e 
e[1] = 414

print('e is now ', e)
print('Changes made to e are NOT reflected for c this time, hinting DEEP COPY', c)

e a duplicate copy of c [100   2   3   4]
e is now  [100 414   3   4]
Changes made to e are NOT reflected for c this time, hinting DEEP COPY [100   2   3   4]


#### In NumPy, the np.copy() function is used to create a copy of an array. By default, np.copy() performs a deep copy of the array. This means that it creates a new array with its own data, independent of the original array.

## <u>np.copy()</u>
#### Purpose: To create a new array that is a deep copy of the original array, meaning that the new array contains a copy of the data, not just a reference to the data.

### Parameters:

#### a: The input array to be copied.
#### order: Specifies the memory layout order for the new array. Options are 'C' for C-style row-major order, 'F' for Fortran-style column-major order, and None for the default behavior.

In [305]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

#### The <u>numpy.fromfunction()</u> function in NumPy is a powerful tool for creating arrays by specifying a function that generates the values of the array. Instead of manually populating an array, you can use numpy.fromfunction() to define the values based on the array’s indices.

### <u>numpy.fromfunction()</u>
#### Purpose: To create an array by applying a function to each coordinate index of the array. This function generates the values of the array based on the indices.

### Parameters:

#### function: A function that takes index arrays as arguments and returns an array of values. The function should accept the indices of the array as input and return the corresponding values.
#### shape: A tuple representing the shape of the output array. This determines the dimensions of the array to be created.

## <u>(In NumPy, the shape of an array is a tuple that represents the dimensions of the array. Each element of the tuple corresponds to the size of the array along a particular axis)</u>

In [58]:
sample1 = np.fromfunction(lambda i, j : i<j, (4, 5))

print(sample1)

[[False  True  True  True  True]
 [False False  True  True  True]
 [False False False  True  True]
 [False False False False  True]]


In [60]:
sample2 = np.fromfunction(lambda i, j : i*j, (3, 3))

print(sample2)

[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]


#### The <u>numpy.fromiter()</u> function in NumPy is used to create an array from an iterable object. It allows you to generate a NumPy array by iterating over a sequence of elements, such as a list, generator, or any object that supports iteration.

### <u>numpy.fromiter()</u>
#### Purpose: To create a NumPy array from an iterable object, which is useful when you have a sequence of values but not a standard array-like object.

### Parameters:

#### iterable: An iterable object (e.g., a list, tuple, or generator) from which to create the array.
#### dtype: Data type of the resulting array. This should be specified to ensure the correct data type for the array. If not specified, NumPy tries to infer the data type from the iterable elements.
#### count: The number of items to read from the iterable. If not specified, it reads until the iterable is exhausted. This is particularly useful when you only need to read a subset of items

In [74]:
iterable1 = (i*i for i in range(5))

# dtype specified as int
sample3 = np.fromiter(iterable1, int)
print(sample3)

iterable2 = (i**i for i in range(5))

# dtype specified as float
sample4 = np.fromiter(iterable2, float)
print(sample4)

[ 0  1  4  9 16]
[  1.   1.   4.  27. 256.]


In [78]:
sample5 = np.fromiter(iterable1, int)

print(sample5)

[]


### The reason you're getting an empty array is that the generator iterable1 is exhausted by the time you pass it to np.fromiter(). In Python, generators are iterated over only once. After they are exhausted, they cannot be reused or iterated over again

In [81]:
sample6 = np.fromstring('223 414', sep=" ")

print(sample6)

[223. 414.]


In [83]:
sample7 = np.fromstring('2,4,1,4', sep=",")

print(sample7)

[2. 4. 1. 4.]


In [314]:
# numpy data types

In [101]:
arr3 = np.array([1, 4, 6, 1, 4, 6])

print(arr3)
print('\nThe dimensions of arr3 is', arr3.ndim)
print('\nThe size of arr3 is', arr3.size)
print('\nThe shape of arr3 is', arr3.shape)
print('\nThe dtype of arr3 is', arr3.dtype)

[1 4 6 1 4 6]

The dimensions of arr3 is 1

The size of arr3 is 6

The shape of arr3 is (6,)

The dtype of arr3 is int32


In [103]:
arr4 = np.array([[4, 1, 4], [0, 8, 2]])

print(arr4)
print('\nThe dimensions of arr4 is', arr4.ndim)
print('\nThe size of arr4 is', arr4.size)
print('\nThe shape of arr4 is', arr4.shape)
print('\nThe dtype of arr4 is', arr4.dtype)

[[4 1 4]
 [0 8 2]]

The dimensions of arr4 is 2

The size of arr4 is 6

The shape of arr4 is (2, 3)

The dtype of arr4 is int32


In [105]:
arr5 = np.array([(1.45, 4.14, 4.56), (4.14, 7.34, 9.43)])

print(arr5)
print('\nThe dimensions of arr4 is', arr5.ndim)
print('\nThe size of arr4 is', arr5.size)
print('\nThe shape of arr4 is', arr5.shape)
print('\nThe dtype of arr4 is', arr5.dtype)

[[1.45 4.14 4.56]
 [4.14 7.34 9.43]]

The dimensions of arr4 is 2

The size of arr4 is 6

The shape of arr4 is (2, 3)

The dtype of arr4 is float64


In [327]:
list(range(5))

[0, 1, 2, 3, 4]

#### The <u>numpy.arange()</u> function in NumPy is used to create an array with evenly spaced values within a specified range. It is similar to Python's built-in range() function but returns a NumPy array instead of a list.

### <u>numpy.arange()</u>
#### Purpose: To generate an array of evenly spaced values between a start value and a stop value (and optionally, with a specified step size).

### Parameters:

#### start: The starting value of the sequence. The default is 0 if not provided.
#### stop: The end value of the sequence, which is not included in the array.
#### step: The spacing between values in the array. The default is 1 if not provided.
#### dtype: The data type of the resulting array. If not specified, it is inferred from the input values

In [108]:
arr6 = np.arange(2.3, 5.6)

print(arr6)

# if step isnot mentioned, by default remains 1

[2.3 3.3 4.3 5.3]


In [3]:
arr7 = np.arange(2.3, 5.6, 0.2)

print(arr7)

[2.3 2.5 2.7 2.9 3.1 3.3 3.5 3.7 3.9 4.1 4.3 4.5 4.7 4.9 5.1 5.3 5.5]


In [112]:
list(arr7)

[2.3,
 2.5,
 2.7,
 2.9000000000000004,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.700000000000001,
 3.9000000000000012,
 4.100000000000001,
 4.300000000000002,
 4.500000000000002,
 4.700000000000002,
 4.900000000000002,
 5.100000000000002,
 5.3000000000000025,
 5.500000000000003]

#### The <u>numpy.linspace()</u> function in NumPy generates an array of evenly spaced values over a specified interval. Unlike numpy.arange(), which uses a step size to determine the spacing between values, numpy.linspace() specifies the number of values you want to generate and calculates the step size accordingly to ensure that the values are evenly spaced.

### <u>numpy.linspace()</u>
#### Purpose: To create an array of evenly spaced values over a specified range, with a specified number of values.

### Parameters:

#### start: The starting value of the sequence.
#### stop: The end value of the sequence, which is included in the array.
#### num: The number of values to generate. The default is 50 if not specified.
#### endpoint: A boolean indicating whether to include the stop value in the array. The default is True.
#### retstep: A boolean indicating whether to return the step size between values. The default is False.
#### dtype: The data type of the resulting array. If not specified, it is inferred from the input values.

In [9]:
arr8 = np.linspace(1, 5, 10)
print(arr8)

# by default the dtype for linspace() is float

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [42]:
arr9 = np.linspace(2, 4, 20)

print(arr9)

[2.         2.10526316 2.21052632 2.31578947 2.42105263 2.52631579
 2.63157895 2.73684211 2.84210526 2.94736842 3.05263158 3.15789474
 3.26315789 3.36842105 3.47368421 3.57894737 3.68421053 3.78947368
 3.89473684 4.        ]


## What is np.logspace()?
### np.logspace() generates numbers spaced evenly on a logarithmic scale, which means that the numbers grow (or shrink) exponentially, rather than linearly.

#### In linear space, numbers increase by a constant difference (e.g., 1, 2, 3, 4, ...).
#### In logarithmic space, numbers increase by a constant ratio (e.g., 1, 10, 100, 1000, ...), where each number is a fixed multiple of the previous one.

## How np.logspace() works
#### When you use np.logspace(), you define a range of exponents (powers) to generate numbers. These numbers are calculated as powers of a base, typically 10 (default base).

### Key Parameters:
#### start: The exponent to start from. The first number will be base ** start
#### stop: The exponent to stop at. The last number will be base ** stop
#### num: How many numbers to generate.
#### base: The base of the logarithmic scale (default is 10, but you can use any base).

In [47]:
arrLog1 = np.logspace(2, 5, 10)

print(arrLog1)

[   100.            215.443469      464.15888336   1000.
   2154.43469003   4641.58883361  10000.          21544.34690032
  46415.88833613 100000.        ]


In [49]:
arrLog2 = np.logspace(2, 5, 10, base=2)

print(arrLog2)

[ 4.          5.0396842   6.34960421  8.         10.0793684  12.69920842
 16.         20.1587368  25.39841683 32.        ]


In [53]:
arrLog3 = np.logspace(0, 3, 4)

print(arrLog3)

[   1.   10.  100. 1000.]


### np.zeros() is a function in NumPy that creates a new array filled with zeros. You can specify the shape and data type of the array.

## Parameters:
### shape: Defines the dimensions of the array (e.g., (3, 4) for a 3x4 array).
### dtype: (Optional) Specifies the data type of the array elements. The default is float.

In [11]:
arrZeros1 = np.zeros(5)

print(arrZeros1)

[0. 0. 0. 0. 0.]


In [15]:
arrZeros2 = np.zeros((3, 4), dtype=int)

print(arrZeros2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
arrZeros3 = np.zeros((3, 4, 3))

print(arrZeros3)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [19]:
arrZeros4 = np.zeros((3, 4, 3, 2))

print(arrZeros4)
print('\nThe dimensions of the array arrZeros4', arrZeros4.ndim)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]

The dimensions of the array arrZeros4 4


### np.ones() is similar to np.zeros(), but instead of filling the array with zeros, it fills the array with ones.

## Parameters
#### shape: Defines the dimensions of the array (e.g., (3, 4) for a 3x4 array).
#### dtype: (Optional) Specifies the data type of the array elements. The default is float.

In [25]:
arrOnes1 = np.ones(4)

print(arrOnes1)
print('\nThe dimensions of the array arrOnes1:', arrOnes1.ndim)
print('\nThe datatype of the array arrOnes1:', arrOnes1.dtype)

[1. 1. 1. 1.]

The dimensions of the array arrOnes1: 1

The datatype of the array arrOnes1: float64


In [27]:
arrOnes2 = np.ones((2, 3))

print(arrOnes2)
print('\nThe dimensions of the array arrOnes2:', arrOnes2.ndim)
print('\nThe datatype of the array arrOnes2:', arrOnes2.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]

The dimensions of the array arrOnes2: 2

The datatype of the array arrOnes2: float64


In [29]:
arrOnes3 = np.ones((2, 3, 4))

print(arrOnes3)
print('\nThe dimensions of the array arrOnes3:', arrOnes3.ndim)
print('\nThe datatype of the array arrOnes3:', arrOnes3.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

The dimensions of the array arrOnes3: 3

The datatype of the array arrOnes3: float64


In [31]:
print(arrOnes3 + 5)

[[[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]

 [[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]]


In [33]:
print(arrOnes3 * 4)

[[[4. 4. 4. 4.]
  [4. 4. 4. 4.]
  [4. 4. 4. 4.]]

 [[4. 4. 4. 4.]
  [4. 4. 4. 4.]
  [4. 4. 4. 4.]]]


#### np.empty() creates a new array without initializing its values, meaning the contents will be whatever is already in memory at the time. This means the values in the array will be random or garbage (uninitialized), unlike np.zeros() or np.ones() which fill the array with specific values (0 or 1, respectively).

#### It can be faster than np.zeros() or np.ones() since it doesn't need to set the values explicitly, but you should only use it when you plan to fill the array immediately afterward.

### Parameters:
#### shape: Defines the dimensions of the array.
#### dtype: (Optional) Specifies the data type of the array elements. The default is float.

In [38]:
garb1 = np.empty((3, 5))

print(garb1)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  2.56765117e-312]]


In [40]:
garb2 = np.empty((3, 6))

print(garb2)

[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.60218491e-306
  7.56587585e-307 1.37961302e-306]
 [1.05699242e-307 8.01097889e-307 1.78020169e-306 7.56601165e-307
  1.02359984e-306 1.42417221e-306]
 [7.56593017e-307 1.78021798e-306 6.89804132e-307 1.78021527e-306
  1.42410974e-306 1.42410974e-306]]


## 1. <u>np.random.rand()</u>: Uniform Distribution
#### np.random.rand() generates random numbers from a uniform distribution over the range [0, 1), meaning the values are uniformly distributed between 0 and 1 (including 0, but excluding 1).

## 2. <u>np.random.randn()</u>: Standard Normal Distribution
#### np.random.randn() generates random numbers from a standard normal distribution (also called a Gaussian distribution) with a mean of 0 and a standard deviation of 1. The values can be both positive and negative, and they are centered around 0.

## 3. <U>np.random.randint()</U>: Random Integers
#### np.random.randint() generates random integers between a specified range (inclusive of the lower bound, exclusive of the upper bound). You can also specify the shape of the output array

In [62]:
arr10 = np.random.randn(3, 4)

print(arr10)

[[-1.47497133 -1.04230771 -0.02201629 -0.37328775]
 [-0.92412645 -1.19567531  1.21633774 -0.21815666]
 [ 0.09860281  1.81391106 -0.5275555  -1.44093779]]


In [64]:
import pandas as pd

df1 = pd.DataFrame(arr10)
df1

0         1         2         3
0 -1.474971 -1.042308 -0.022016 -0.373288
1 -0.924126 -1.195675  1.216338 -0.218157
2  0.098603  1.813911 -0.527556 -1.440938

In [66]:
arr11 = np.random.rand(3, 4)

print(arr11)

[[0.88295569 0.39175338 0.851398   0.30594115]
 [0.14603558 0.44594109 0.23271368 0.03051683]
 [0.42161083 0.06058698 0.88645534 0.59614896]]


In [68]:
arr12 = np.random.randint(1, 110, (3, 4))

print(arr12)

[[ 60  49 109   8]
 [ 94  49   5  82]
 [ 73  50 101  69]]


In [70]:
arr13 = np.random.randint(1, 110, (300, 4))

print(arr13)

[[27 70 34 23]
 [34 49 36 40]
 [20  8 42 28]
 ...
 [71 24 10 11]
 [67 93 33 70]
 [ 2 29  4 41]]


In [72]:
df2 = pd.DataFrame(arr13)
# pd.DataFrame(arr7).to_csv('test.csv')

df2

0   1   2   3
0    27  70  34  23
1    34  49  36  40
2    20   8  42  28
3    23  30  61  88
4    54   1  39   1
..   ..  ..  ..  ..
295  24  60  32  78
296   1   2  87  66
297  71  24  10  11
298  67  93  33  70
299   2  29   4  41

[300 rows x 4 columns]

In [74]:
arr14 = np.random.rand(3, 4)

print(arr14)

[[0.30573535 0.21681913 0.38043186 0.95969375]
 [0.64523354 0.72354434 0.00612358 0.15166229]
 [0.68214459 0.03266452 0.98621842 0.25070391]]


#### The np.reshape() function in NumPy is used to change the shape of an array without changing its data. Essentially, it gives a new shape to an existing array, but the total number of elements must remain the same.

## np.reshape(array, new_shape)
#### array: The array you want to reshape.
#### new_shape: The desired shape, specified as a tuple (rows, columns). The total number of elements in new_shape must match the number of elements in the original array.

In [76]:
print(arr14.reshape(6, 2))

[[0.30573535 0.21681913]
 [0.38043186 0.95969375]
 [0.64523354 0.72354434]
 [0.00612358 0.15166229]
 [0.68214459 0.03266452]
 [0.98621842 0.25070391]]


In [78]:
print(arr14.reshape(3, -1))

[[0.30573535 0.21681913 0.38043186 0.95969375]
 [0.64523354 0.72354434 0.00612358 0.15166229]
 [0.68214459 0.03266452 0.98621842 0.25070391]]


In [80]:
print(arr14.reshape(2, -1))

[[0.30573535 0.21681913 0.38043186 0.95969375 0.64523354 0.72354434]
 [0.00612358 0.15166229 0.68214459 0.03266452 0.98621842 0.25070391]]


In [82]:
print(arr14.reshape(-1, 2))

[[0.30573535 0.21681913]
 [0.38043186 0.95969375]
 [0.64523354 0.72354434]
 [0.00612358 0.15166229]
 [0.68214459 0.03266452]
 [0.98621842 0.25070391]]


In [84]:
print(arr14)

[[0.30573535 0.21681913 0.38043186 0.95969375]
 [0.64523354 0.72354434 0.00612358 0.15166229]
 [0.68214459 0.03266452 0.98621842 0.25070391]]


In [88]:
arr14[1]

array([0.64523354, 0.72354434, 0.00612358, 0.15166229])

In [90]:
arr14[1][1]

0.7235443377807841

In [92]:
arr14[2:]

array([[0.68214459, 0.03266452, 0.98621842, 0.25070391]])

In [94]:
arr14[2:, 2]

array([0.98621842])

In [96]:
arr15 = np.random.randint(1, 100, (3,5))

print(arr15)

[[71 14 53 80 36]
 [82  8 63 86 93]
 [17 52 68  2 61]]


In [98]:
arr16 = np.random.randint(1, 100, (5,5))

print(arr16)

[[53 27 35  3 29]
 [61 72 86 51 32]
 [78 59 17 13 20]
 [42 75 44 84 63]
 [69 12 16 74 92]]


In [100]:
arr15 > 50

array([[ True, False,  True,  True, False],
       [ True, False,  True,  True,  True],
       [False,  True,  True, False,  True]])

In [104]:
print(arr15[arr15 > 50])

[71 53 80 82 63 86 93 52 68 61]


In [106]:
print(arr15)

[[71 14 53 80 36]
 [82  8 63 86 93]
 [17 52 68  2 61]]


In [108]:
print(arr15[2:4, [1, 2]])

[[52 68]]


In [467]:
print(arr15[0][0])

42

In [112]:
arr16[0][0] = 500

print(arr16)

[[500  27  35   3  29]
 [ 61  72  86  51  32]
 [ 78  59  17  13  20]
 [ 42  75  44  84  63]
 [ 69  12  16  74  92]]


In [116]:
arr17 = np.random.randint(1, 3, (3, 2))
print(arr17)

arr18 = np.random.randint(1, 3, (3, 2))
print(arr18)

[[2 2]
 [1 2]
 [2 2]]
[[1 1]
 [1 1]
 [2 1]]


In [118]:
arr17 + arr18

array([[3, 3],
       [2, 3],
       [4, 3]])

In [120]:
arr17 - arr18

array([[1, 1],
       [0, 1],
       [0, 1]])

In [122]:
arr17 / arr18

array([[2., 2.],
       [1., 2.],
       [1., 2.]])

In [124]:
arr17 * arr18

array([[2, 2],
       [1, 2],
       [4, 2]])

In [128]:
arr19 = np.random.randint(1, 3, (2, 3))

arr20 = arr17 @ arr19 # matrix multiplication
print(arr20)

[[4 6 4]
 [3 4 3]
 [4 6 4]]


In [130]:
arr20 / 0

C:\Users\karth\AppData\Local\Temp\ipykernel_7312\2847945382.py:1: RuntimeWarning: divide by zero encountered in divide
  arr20 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [132]:
arr20 ** 2

array([[16, 36, 16],
       [ 9, 16,  9],
       [16, 36, 16]])

In [507]:
# broadcasting

#### In NumPy, broadcasting refers to the process of performing arithmetic operations (like addition, subtraction, multiplication, etc.) on arrays of different shapes. Broadcasting allows NumPy to "stretch" smaller arrays so that they have compatible shapes for element-wise operations with larger arrays, without actually copying the data.

#### Broadcasting simplifies array operations and makes them more efficient by avoiding the need to explicitly reshape or replicate arrays.

### <u>Rules for Broadcasting</u>
#### Broadcasting follows specific rules to determine how arrays of different shapes can be compatible for element-wise operations:

#### Matching Dimensions: If the two arrays have the same dimension sizes, they are directly compatible.

#### Dimension of Size 1: If one of the dimensions has size 1, it can be stretched to match the size of the other dimension.

#### Trailing Dimensions: When arrays have different numbers of dimensions, NumPy will align them by comparing the shapes starting from the rightmost dimension and move left.

##### If these rules are satisfied, NumPy broadcasts the smaller array to match the shape of the larger array.


In [138]:
arr21 = np.zeros((4, 4))

row = np.array([1, 2, 3, 4])

print(arr21)
print('\n', row)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [1 2 3 4]


In [142]:
print(arr21 + row)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [144]:
column = row.T

print(column)
# It is NOT possible to take transpose of 1D array

[1 2 3 4]


In [146]:
col = np.array([[1, 2, 3, 4]])
print('Before taking transpose', col)

col = col.T
print('\nAfter Transpose:\n')
print(col)

Before taking transpose [[1 2 3 4]]

After Transpose:

[[1]
 [2]
 [3]
 [4]]


In [148]:
print(arr21 + col)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [150]:
arr22 = np.random.randint(1, 4, (3, 4))

print(arr22)

[[3 3 2 1]
 [3 3 2 1]
 [2 1 2 3]]


In [152]:
np.sqrt(arr22)

array([[1.73205081, 1.73205081, 1.41421356, 1.        ],
       [1.73205081, 1.73205081, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356, 1.73205081]])

In [154]:
np.exp(arr22)

array([[20.08553692, 20.08553692,  7.3890561 ,  2.71828183],
       [20.08553692, 20.08553692,  7.3890561 ,  2.71828183],
       [ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692]])

In [156]:
np.log10(arr22)

array([[0.47712125, 0.47712125, 0.30103   , 0.        ],
       [0.47712125, 0.47712125, 0.30103   , 0.        ],
       [0.30103   , 0.        , 0.30103   , 0.47712125]])