In [1]:
import numpy as np

arr = np.random.randint(1, 10, (3, 4))
print(arr)

[[4 7 4 7]
 [8 5 9 9]
 [4 8 7 2]]


#### The np.reshape() function in NumPy is used to change the shape of an array without changing its data. Essentially, it gives a new shape to an existing array, but the total number of elements must remain the same.

## <u>np.reshape(array, new_shape)</u> parameters:
#### array: The array you want to reshape.
#### new_shape: The desired shape, specified as a tuple (rows, columns). The total number of elements in new_shape must match the number of elements in the original array.

In [5]:
arr.reshape(6, 2)

array([[4, 7],
       [4, 7],
       [8, 5],
       [9, 9],
       [4, 8],
       [7, 2]])

### What happens when passing negative values for rows or columns?
##### If you pass a negative value in the new_shape, NumPy automatically infers the dimension based on the total number of elements. The negative value tells NumPy to figure out that dimension.

In [7]:
arr.reshape(1, -34)

array([[4, 7, 4, 7, 8, 5, 9, 9, 4, 8, 7, 2]])

In [11]:
print(arr.T)
print('\nThe actual array remains unchanged', arr)

[[4 8 4]
 [7 5 8]
 [4 9 7]
 [7 9 2]]

The actual array remains unchanged [[4 7 4 7]
 [8 5 9 9]
 [4 8 7 2]]


### The flatten() function in NumPy is used to convert a multi-dimensional array into a 1D (one-dimensional) array. Essentially, it collapses the array, no matter its original shape, into a single continuous line of elements.

In [24]:
# array.flatten(order='C')

### order (optional): Determines the order in which the elements are read to form the flattened array.
##### 'C' (default): Row-major order (C-style), meaning elements are read row by row.
##### 'F': Column-major order (Fortran-style), meaning elements are read column by column.
##### 'A': ‘F’ if the array is Fortran-contiguous in memory, ‘C’ otherwise.
##### 'K': Flatten in the order the elements appear in memory (may not be C or Fortran contiguous).

In [17]:
arr.flatten()

array([6, 7, 4, 3, 5, 2, 1, 7, 9, 8, 4, 5])

In [21]:
arr1 = np.array([1, 2, 3, 4, 5])

print('The array arr', arr1)
print('\nThe dimensions of the array arr is', arr1.ndim)

The array arr [1 2 3 4 5]

The dimensions of the array arr is 1


### <u>np.expand_dims()</u> in NumPy is used to add a new axis to an array, effectively increasing its dimensionality. This function allows you to insert a new axis (dimension) at a specified position in the shape of an array.

In [ ]:
# np.expand_dims(array, axis)

#### array: The array to which you want to add a new dimension.
#### axis: The position where the new axis will be inserted. This can be any integer (positive or negative) between 0 and ndim, where ndim is the number of dimensions of the array.

In [29]:
arr1_r = np.expand_dims(arr1, axis=1)

print(arr1_r)
print('\nThe array dimensions after expanding', arr1_r.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]]

The array dimensions after expanding 2


In [31]:
arr1_c = np.expand_dims(arr1, axis=0)

print(arr1_c)
print('\nThe array dimensions after expanding', arr1_c.ndim)

[[1 2 3 4 5]]

The array dimensions after expanding 2


#### np.squeeze() in NumPy removes single-dimensional entries (dimensions of size 1) from the shape of an array. This is useful when you want to remove unnecessary dimensions, such as after using functions like expand_dims() or when dealing with arrays that have extra dimensions from broadcasting or reshaping.

## <u>np.squeeze(array, axis=None)</u> parameters:
#### array: The array you want to squeeze.
#### axis (optional): The specific axis (or axes) you want to squeeze. If not specified, all axes of size 1 are removed

In [35]:
print(arr)

print('\n', np.squeeze(arr))

[[4 7 4 7]
 [8 5 9 9]
 [4 8 7 2]]

 [[4 7 4 7]
 [8 5 9 9]
 [4 8 7 2]]


In [39]:
data = np.array([[1], [2], [3]])

print(data)
print('\nAfter Squeezing', np.squeeze(data))

[[1]
 [2]
 [3]]

After Squeezing [1 2 3]


### np.repeat()
#### np.repeat() is used to repeat the elements of an array along a specified axis. You can repeat elements a specified number of times, either along the entire array or along a specific axis.

### <u>np.repeat(array, repeats, axis=None)</u> Parameters:
#### array: The input array.
#### repeats: The number of times to repeat each element. This can be a scalar (same number of repeats for all elements) or an array (different number of repeats for each element).
#### axis (optional): The axis along which to repeat the values. If not specified, the array is flattened and repeated

In [42]:
print(arr1)

print('Repeat array entries by 3', np.repeat(arr1, 3))

[1 2 3 4 5]
Repeat array entries by 3 [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


### <u>np.roll()</u>
#### np.roll() is a function in NumPy used to "roll" or shift the elements of an array along a specified axis. The elements that are shifted out on one end are reintroduced on the other end, effectively wrapping the array.

### <u>np.roll(array, shift, axis=None)</u> Parameters:
#### array: The input array to be rolled.
#### shift: The number of places by which elements are shifted. If shift is positive, elements are shifted to the right (or down along the axis), and if negative, elements are shifted to the left (or up).
#### axis (optional): The axis along which to roll the elements. If not specified, the array is flattened, and elements are rolled along the 1D version of the array.

In [46]:
print(arr1)

print('Roll array entries by 2', np.roll(arr1, 2))

[1 2 3 4 5]
Roll array entries by 2 [4 5 1 2 3]


#### np.diag() is a NumPy function that either extracts the diagonal elements from a matrix or creates a diagonal matrix from a given array. The behavior of np.diag() depends on whether the input is a 1D or 2D array.

### <u>np.diag(v, k=0)</u> parameters:
#### v: The input array. It can be either 1D (to create a diagonal matrix) or 2D (to extract the diagonal).
#### k (optional): The diagonal to extract or set.
##### k=0 refers to the main diagonal.
##### k>0 refers to diagonals above the main diagonal.
##### k<0 refers to diagonals below the main diagonal

In [45]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [87]:
np.diag(arr1, k = 1)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

In [52]:
arr2 = np.random.randint(1, 10, (3, 4))
arr3 = np.random.randint(1, 10, (3, 4))

print(arr2)
print('\n', arr3)

[[4 3 7 6]
 [1 2 4 5]
 [1 2 4 5]]

 [[9 2 5 9]
 [2 2 1 2]
 [6 6 8 6]]


In [54]:
arr2 + arr3

array([[13,  5, 12, 15],
       [ 3,  4,  5,  7],
       [ 7,  8, 12, 11]])

In [56]:
arr2 / arr3

array([[0.44444444, 1.5       , 1.4       , 0.66666667],
       [0.5       , 1.        , 4.        , 2.5       ],
       [0.16666667, 0.33333333, 0.5       , 0.83333333]])

In [58]:
arr2 - arr3

array([[-5,  1,  2, -3],
       [-1,  0,  3,  3],
       [-5, -4, -4, -1]])

In [60]:
arr2 % arr3

array([[4, 1, 2, 6],
       [1, 0, 0, 1],
       [1, 2, 4, 5]])

In [62]:
arr2 ** arr3

array([[  262144,        9,    16807, 10077696],
       [       1,        4,        4,       25],
       [       1,       64,    65536,    15625]])

In [64]:
arr2 & arr3

array([[0, 2, 5, 0],
       [0, 2, 0, 0],
       [0, 2, 0, 4]])

In [66]:
~arr2

array([[-5, -4, -8, -7],
       [-2, -3, -5, -6],
       [-2, -3, -5, -6]])

In [68]:
arr2 | arr3

array([[13,  3,  7, 15],
       [ 3,  2,  5,  7],
       [ 7,  6, 12,  7]])

In [70]:
arr2 > arr3

array([[False,  True,  True, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [74]:
arr4 = np.array(['molly', 'weasly'])

In [76]:
np.char.upper(arr4)

array(['MOLLY', 'WEASLY'], dtype='<U6')

In [78]:
np.char.title(arr4)

array(['Molly', 'Weasly'], dtype='<U6')

In [80]:
np.char.capitalize(arr4)

array(['Molly', 'Weasly'], dtype='<U6')

In [84]:
np.sin(arr2)

array([[-0.7568025 ,  0.14112001,  0.6569866 , -0.2794155 ],
       [ 0.84147098,  0.90929743, -0.7568025 , -0.95892427],
       [ 0.84147098,  0.90929743, -0.7568025 , -0.95892427]])

In [87]:
np.cos(arr2)

array([[-0.9899925 , -0.41614684,  0.75390225, -0.91113026],
       [-0.9899925 , -0.41614684, -0.65364362, -0.41614684],
       [-0.14550003, -0.41614684, -0.65364362,  0.96017029]])

In [89]:
np.tan(arr2)

array([[-0.14254654, -2.18503986,  0.87144798, -0.45231566],
       [-0.14254654, -2.18503986,  1.15782128, -2.18503986],
       [-6.79971146, -2.18503986,  1.15782128, -0.29100619]])

In [91]:
np.tanh(arr2)

array([[0.99505475, 0.96402758, 0.99999834, 0.99999997],
       [0.99505475, 0.96402758, 0.9993293 , 0.96402758],
       [0.99999977, 0.96402758, 0.9993293 , 0.99998771]])

In [93]:
np.log10(arr2)

array([[0.47712125, 0.30103   , 0.84509804, 0.95424251],
       [0.47712125, 0.30103   , 0.60205999, 0.30103   ],
       [0.90308999, 0.30103   , 0.60205999, 0.77815125]])

In [95]:
np.exp(arr2)

array([[2.00855369e+01, 7.38905610e+00, 1.09663316e+03, 8.10308393e+03],
       [2.00855369e+01, 7.38905610e+00, 5.45981500e+01, 7.38905610e+00],
       [2.98095799e+03, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02]])

In [97]:
np.sqrt(arr2)

array([[1.73205081, 1.41421356, 2.64575131, 3.        ],
       [1.73205081, 1.41421356, 2.        , 1.41421356],
       [2.82842712, 1.41421356, 2.        , 2.44948974]])

In [101]:
np.power(arr2, 2)

array([[ 9,  4, 49, 81],
       [ 9,  4, 16,  4],
       [64,  4, 16, 36]], dtype=int32)

In [103]:
np.mean(arr2)

4.333333333333333

In [105]:
np.median(arr2)

3.5

In [107]:
np.std(arr2)

2.4267032964268394

In [109]:
np.var(arr2)

5.888888888888888

In [111]:
np.min(arr2)

2

In [113]:
np.max(arr2)

9