In [6]:
import numpy as np
arr = np.array([1, 2, 3, 10, 5, 21, 7, 17, 88, 22])

print('Before Sorting', arr)
print('\nAfter Sorting', np.sort(arr))

Before Sorting [ 1  2  3 10  5 21  7 17 88 22]

After Sorting [ 1  2  3  5  7 10 17 21 22 88]


### The searchsorted() function in NumPy is used to find indices in a sorted array where elements should be inserted to maintain order. It returns the index at which the specified value(s) can be inserted into the array so that the order of the array is preserved.

## <u>numpy.searchsorted(sorted_array, values, side='left')</u> Parameters:
#### sorted_array: The input array, which must be sorted in ascending order.
#### values: The value(s) to be inserted.
#### side: This parameter can be 'left' or 'right'.
##### 'left': If the value is found, insert to the left of the first occurrence.
##### 'right': If the value is found, insert to the right of the last occurrence.
## Returns:
### It returns the index (or indices if multiple values are provided) where the value(s) should be inserted.

In [10]:
arr_sorted = np.sort(arr)
print('Sorted Array:', arr_sorted)
np.searchsorted(arr_sorted, 14)

Sorted Array: [ 1  2  3  5  7 10 17 21 22 88]


6

### The count_nonzero() function in NumPy counts the number of non-zero elements in an array.

## <u>numpy.count_nonzero(arr, axis=None)</u> Parameters:
#### arr: The input array in which to count non-zero elements.
#### axis: (Optional) The axis or axes along which to count non-zero values.
##### If None (the default), it counts non-zero values across the entire array.
##### If an integer is provided, it counts along the specified axis.

## Returns:
### It returns the number of non-zero elements in the array, or along a specified axis.

In [15]:
arr1 = np.array([0, 34, 56, 0, 3, 0, 0])

np.count_nonzero(arr1)

3

### The where() function in NumPy is a versatile tool used for element-wise selection or condition-based indexing. It returns the indices of elements that satisfy a specified condition or can be used to choose elements based on a condition from two arrays.

## Syntax 1 (Condition-based indexing):
### numpy.where(condition)
#### This form returns the indices where the condition is True.

## Syntax 2 (Element-wise selection):
### numpy.where(condition, x, y)
#### This form selects elements from either x or y, depending on whether the condition is True or False.

### Parameters:
#### condition: A boolean array or condition that is applied to the array.
#### x: Values to choose if the condition is True (optional in syntax 1).
#### y: Values to choose if the condition is False (optional in syntax 1).

### Returns:
#### In Syntax 1, it returns the tuple of arrays corresponding to the indices where the condition is True.
#### In Syntax 2, it returns an array with elements from x where the condition is True and from y where it is False.

In [21]:
print(arr)
print('\nIndices of Entries in the array arr greater than 6\n')
np.where(arr > 6)

[ 1  2  3 10  5 21  7 17 88 22]

Indices of Entries in the array arr greater than 6



(array([3, 5, 6, 7, 8, 9], dtype=int64),)

### The extract() function in NumPy is used to extract elements from an array that satisfy a given condition. It is essentially a way to filter an array based on a condition, returning a one-dimensional array of elements that meet the condition.

## Syntax:
### numpy.extract(condition, arr)
## Parameters:
#### condition: An array-like object (usually boolean) that specifies which elements to extract. Only True values in the condition will result in element extraction.
#### arr: The input array from which to extract elements.
### Returns:
#### It returns a one-dimensional array of elements from the input array that meet the condition.

In [19]:
np.extract(arr > 6, arr)

array([10, 21,  7, 17, 88, 22])

In [23]:
arr.byteswap()

array([  16777216,   33554432,   50331648,  167772160,   83886080,
        352321536,  117440512,  285212672, 1476395008,  369098752])

In [27]:
a = np.copy(arr)

In [31]:
b = arr.view()

In [33]:
b

array([ 1,  2,  3, 10,  5, 21,  7, 17, 88, 22])

In [35]:
b[0] = 46

In [37]:
b

array([46,  2,  3, 10,  5, 21,  7, 17, 88, 22])

In [39]:
arr

array([46,  2,  3, 10,  5, 21,  7, 17, 88, 22])

In [41]:
import numpy.matlib as nm

In [43]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [45]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [47]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [51]:
arr2 = np.random.randint([[2, 3], [4, 5]])

In [53]:
arr3 = np.random.randint([[6, 2], [10, 2]])

In [57]:
np.dot(arr2, arr3)

array([[ 2,  2],
       [14,  5]])

In [59]:
arr2 @ arr3

array([[ 2,  2],
       [14,  5]])